### DISCUSSION TITLE
Specific color for invalid names

### DISCUSSION THREAD

**Discussion by pml-lang** [tajmone/Sublime-PML#6] [Syntax Elements]
If I write:
```
[doc
]
```
... the whole text is highlighted. That's ok.

However If I write:
```
[do
]
```
... then `[do` is highlighted in the same color as before, but `]` isn't highlighted.
As this is an invalid tag, it would be nice to display the whole text (or at least `[do`) in an 'error' color.

The same could be done for attributes. An invalid attribute name is displayed in an 'error' color.

**Comment by tajmone** [comment]
> As this is an invalid tag, it would be nice to display the whole text (or at least `[do`) in an 'error' color

This is in the TODO list, [as annotated in the source code]

```yaml
  maybe_node:
    - include: block_nodes
    - include: inline_nodes
    - include: text_processing_nodes
    - include: unknown_node
    # TODO: When all nodes are implemented, all that's left is an
    #       unescaped '[', which should be scoped as invalid/error!
    - include: bail-out
```

> ... then `[do` is highlighted in the same color as before, but `]` isn't highlighted.

The color depends on the scheme you're using, with my scheme they are differently colored. Currently, `[do` is scoped as `entity.name.tag.other.begin.pml`, which is the `unknown_node` element, just a temporary fallback to cover unimplemented nodes:

```yaml
  unknown_node:
    # This is a just a temporary scope, to cover the unimplemented nodes.
    # It will be removed once all nodes are implemented.
    - match: '\[[a-z][a-z_]*\b'
      scope: entity.name.tag.other.begin.pml
```

The fact that the `]` isn't highlighted seems a bug that was introduced by some later changes. I'll have to look at this, the syntax tests were supposed to cover it, but I must have forgotten this test for unknown tags.

### On Using `invalid` Scope

Using the `invalid` scope right now would just look bad, since there too many unimplemented nodes still. Once all nodes and attributes are implemented, than we could add this feature, but I'd like to test it first.

The problem is that it might lead to unpleasant typing, since incomplete node names would always show as invalid, until they're fully typed. You can see this already if you manually type `[doc`: it changes color once you've typed the final `c`. But since the `invalid` scope is usually highlighted with a red background in most color schemes, it would look bad.

This is the main reason why the `invalid` scope is rarely used, expect maybe to cover specific contexts (e.g. a string where string are not allowed), or longer than expected elements, etc.

Sublime PML currently uses the `invalid` scope to highlight out-of-range dates and times (only where they're expected), and as you can see when it does you get a really strong background color catching the attention.

Also, if a new tag or attribute is added to the language, it would show up as invalid until the syntax is updated. So this has to be carefully evaluated first.



[as annotated in the source code]: https://github.com/tajmone/Sublime-PML/blob/d3ffb8d/PML.sublime-syntax#L91
