### ISSUE TITLE
Attributes Lines Continuation after Node Tag

### ISSUE THREAD

**Issue by tajmone** [tajmone/Sublime-PML#26]
Currently, the `attributes` context allows a line-continuation `\` before any attributes were found,e .g.:

```pml
[ch \
    title = Inline Fonts
```

which is incorrect, for in real case usage the `\` can only follow an attribute, not the the node tag.

I should find a way to fix this. The problem is that the current solution makes it easier to track line-continuation slashes `\` between an attribute and the next one:

```yaml
  attributes:
    - include: line_continuation
    - include: pop-at-TagEnd
    - include: pop-at-EOL
    - include: attr_date
    - include: attr_time
    - include: attr_id
```
because matched attributes contexts, when they find the non-consuming lookahead `(?=\s*\\$)` they pop back to their `attributes` parent context, which is the one that will actually match and scope the `\`.
